### ISSUE TITLE
[Bug]: Endpoint only generates data once with Octane

### ISSUE THREAD

**Issue by skipworkgh** [spatie/laravel-prometheus#6]
### What happened?

When serving the `/prometheus` endpoint with Octane, it will only generate the results on the first request to the endpoint in the same process. After that, no content is displayed on the endpoint.

### How to reproduce the bug

1. Install new Laravel app
2. Install and configure Laravel Horizon
3. Install and configure Laravel Octane (Swoole)
4. Install this package
5. Enable the Laravel Horizon Gauges
6. Start Laravel Octane
7. Request the `/prometheus` endpoint to get the expected results
8. Request the `/prometheus` endpoint again to get an empty response

### Package Version

1.0.0

### PHP Version

8.2.7

### Laravel Version

10.13.5

### Which operating systems does with happen with?

Linux

### Notes

I've only tested this with Octane and Swoole.

**Comment by skipworkgh** [comment]
Using `singleton()` instead of `scoped()` [here](https://github.com/spatie/laravel-prometheus/blob/main/src/PrometheusServiceProvider.php#L32), actually resolves the issue.

**Comment by freekmurze** [comment]
Really strange! Others are reporting this too, so I'm going to change it to `singleton` now and tag a new release.
